/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CW.modelo.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import CW.modelo.service.ProdutosService;
import CW.modelo.entidade.Produtos;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author caiua
 */
public final class ListarProdutos extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form ListarProdutos
     */
    public ListarProdutos() {
        initComponents();
        
        jComboBox1.removeAllItems();
        
        jComboBox1.addItem("Nome");
        jComboBox1.addItem("Código");
        jComboBox1.addItem("Quantidade");
        jTable1.setAutoCreateColumnsFromModel(rootPaneCheckingEnabled);
        jTable1.setShowGrid(false);
        jButton1.addActionListener(this);
        Listar(produtosIn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jTable1.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Preço", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jComboBox1)
                    .addComponent(jTextField1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    // variaveis
    private final Object[] colunas = {"Código","Nome","Preço","Quantidade"};
    DefaultTableModel tableModel = new DefaultTableModel(colunas,0){
        @Override
        public boolean isCellEditable(int row, int column) {
        //all cells false
            return false;
        }
    };
    ProdutosService produtosService = new ProdutosService();
    public final List<Produtos> produtosIn = produtosService.listarProdutos();;
    
    
    @Override
    public void actionPerformed(ActionEvent e){
        Buscar();
    }
    
    public void Listar(List<Produtos> produtos){
        
        tableModel = new DefaultTableModel(colunas,0);
        
        //int i =0;
        for (Produtos produto : produtos) {
            //System.out.println(produto.getNome());
            Object[] data = new Object[4];
            data[0] = produto.getCodigo();
            data[1] = produto.getNome();
            data[2] = String.format("%.2f",produto.getPreco());
            data[3] = produto.getQuantidade();
            tableModel.addRow(data);
            jTable1.setModel(tableModel);

        }
    }
    
    public List<Produtos> buscarNome(String nome){
        
        int i = 0;
        boolean encontrado = false;
        List<Produtos> produtosFiltrados = new ArrayList<>(); 
        
        while (i < produtosIn.size()){ 
            
            encontrado = produtosIn.get(i).getNome().contains(nome.toUpperCase());
            if(encontrado){
                produtosFiltrados.add(produtosIn.get(i));
            }
            i++;
                       
        }
        
        return produtosFiltrados;
        
        
    }

    public List<Produtos> buscarQuantidade(int quantidade){
        
        int i = 0;
        boolean encontrado = false;
        List<Produtos> produtosFiltrados = new ArrayList<>(); 
        
        while (i < produtosIn.size()){ 
            
            encontrado = (quantidade == produtosIn.get(i).getQuantidade());
            if(encontrado){
                produtosFiltrados.add(produtosIn.get(i));
            }
            i++;
                       
        }
        
        return produtosFiltrados;
        
        
    }    

    public List<Produtos> buscarCodigo(long codigo){
        
        int i = 0;
        boolean encontrado = false;
        List<Produtos> produtosFiltrados = new ArrayList<>(); 
        
        while (i < produtosIn.size()){ 
            
            encontrado = (codigo == produtosIn.get(i).getCodigo());
            if(encontrado){
                produtosFiltrados.add(produtosIn.get(i));
            }
            i++;
                       
        }
        
        return produtosFiltrados;
        
        
    }   
    
    public void Buscar(){
        
     
        switch(jComboBox1.getSelectedIndex()){
            
            case 0: //nome
                Listar(buscarNome(jTextField1.getText()));
                break;
                
            case 1: //codigo
                Listar(buscarCodigo(Long.parseLong(jTextField1.getText())));
                break;
              
            case 2: //Quant
                Listar(buscarQuantidade(Integer.parseInt(jTextField1.getText())));
                break;
            
        }
                
   }
    
  
}

